### PR TITLE
serial port support

### PR DESCRIPTION
**Pull request by agentbooth**
Hi @philpem -- here is the serial port support I've been working on. It took some doing to understand exactly what was going on with the 3b1 black box and how the i8274 works but finally figured it out. 

This uses a PTY on linux. I used minicom for testing. Some additional comments on usage at the start of `i8274.c`. Not sure how to support this on other platforms but figure that can be left for another day.

@arnoldrobbins - please check this out too when you get a chance.

Hopefully this works for you guys, but let me know if you run into issues.

   Jesse

### CODE REVIEW

**Comment by philpem** [comment]
I assume this is the onboard serial port?

Does the Combo Card use the same chip?

**Comment by agentbooth** [comment]
Yes this is the onboard serial port. I haven’t looked into the Combo Card.

**Comment by arnoldrobbins** [comment]
@shadyjesse The emulation of the serial port is great, but poor users (like me) need to know how to take advantage of it now that it's there.

To that end can you add a README_SERIAL.md file (or some such) that explains how to make use of this from both the Unix and the Linux side?  For example, on Unix, do you need to edit inittab for a login?  What about using kermit or some other program to transfer files in and out over the serial port? Thanks!

**Comment by agentbooth** [comment]
Good idea. I’ll try to write up some usage notes, there are some notes at the top of the i8274.c that I can use for a start. I just wanted to get the code checked in as I’d been staring at it too long.

**Comment by agentbooth** [comment]
@philpem @arnoldrobbins I checked in README.serial.md that includes some updated instructions on the serial port usage. 

Phil, I don't have anything else pending so please review when you have a chance.

**Comment by philpem** [comment]
Nice work! :)

**Pull request merged**
