### PR TITLE
SDL 2 migration, grabbing mouse now works much better

### PR DESCRIPTION
**Pull request by agentbooth**
Hey Phil. This worked fine for me on my linux PC, would be good to test on other environments. I'd like to test on my Raspberry Pi. There is likely a better optimized version of the surface/texture handling, but this basic conversion seemed to work. Grabbing the mouse with F10 works much better which was a nice bonus. I didn't run into an issue with the timers, just had to change the type of the timer callbacks.

### CODE REVIEW

**Comment by philpem** [comment]
Nice work! Merged!

Looks like this paves the way for #7, which would move the LEDs down, perhaps make them larger, and add icons for floppy and hard drive access too.

**Comment by agentbooth** [comment]
Hey Phil -- thanks for getting this merged.  There is probably a more optimized version of the SDL2 implementation but I don't know enough about the SDL details to address that. Also might be some issues with the Alpha channel on some systems but correctly worked on Raspberry Pi, and my linux x86. I have the LED's as 16x16 (instead of the 8x8 checked in) if you'd prefer the larger icons. I also can check in the source .png image if you want to let me know where to put it.

**Comment by philpem** [comment]
I think optimisation can wait until later, getting it working is always the priority for me. That ignores the obvious caveat of it being usable!

Alpha channel - I haven't seen any issues on x86_64 Linux, if that's an issue I'm sure someone will raise it :)

Re larger LEDs - feel free to check that in on another PR, but I think it'd need to be done more like a status line. 16x16 times four LEDs would cover a fair bit of the bottom corner of the screen. This might also reduce the impact of any alpha-channel issues.

**Comment by agentbooth** [comment]
Ah yes, I remember now -- that's why I went to 8x8 instead of the original 16x16 so it would obscure less of the bottom right corner. 16 pixel status bar in the future sounds like a good plan.

**Pull request merged**
